function onCreate()
  makeLuaSprite('essacidadeae', 'exe/endless-a/Fim3',-920,-350)
  scaleObject('essacidadeae', 1.2, 1.2)
  addLuaSprite('essacidadeae', false)
  makeLuaSprite('posteEstranhoxd', 'exe/endless-a/Fim2',-920,-350)
  scaleObject('posteEstranhoxd', 1.2, 1.2)
  addLuaSprite('posteEstranhoxd', false)
  makeLuaSprite('ochão', 'exe/endless-a/Fim1',-920,-350)
  scaleObject('ochão', 1.2, 1.2)
  addLuaSprite('ochão', false)
end